version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
